- name: Armazenar facts em múltiplos destinos
  hosts: "{{ target_hosts | default('all') }}"
  tasks:
    - name: Coletar facts
      setup:
    - name: Debugar facts coletados
      debug:
        var: ansible_facts
